// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoreScrapper.Data;

#nullable disable

namespace StoreScrapper.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260111170000_AddProductNameColumn")]
    partial class AddProductNameColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationHistoryProductSku", b =>
                {
                    b.Property<int>("NotificationHistoriesId")
                        .HasColumnType("integer")
                        .HasColumnName("notification_histories_id");

                    b.Property<int>("ProductSkusId")
                        .HasColumnType("integer")
                        .HasColumnName("product_skus_id");

                    b.HasKey("NotificationHistoriesId", "ProductSkusId")
                        .HasName("pk_notification_history_product_sku");

                    b.HasIndex("ProductSkusId")
                        .HasDatabaseName("ix_notification_history_product_sku_product_skus_id");

                    b.ToTable("notification_history_product_sku", (string)null);
                });

            modelBuilder.Entity("StoreScrapper.Models.Entities.Adapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_adapters");

                    b.ToTable("adapters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Zara"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PullAndBear"
                        });
                });

            modelBuilder.Entity("StoreScrapper.Models.Entities.JobExecutionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<int?>("NotificationHistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("notification_history_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.HasKey("Id")
                        .HasName("pk_job_execution_logs");

                    b.HasIndex("NotificationHistoryId")
                        .HasDatabaseName("ix_job_execution_logs_notification_history_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_job_execution_logs_product_id");

                    b.ToTable("job_execution_logs", (string)null);
                });

            modelBuilder.Entity("StoreScrapper.Models.Entities.NotificationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailBody")
                        .HasColumnType("text")
                        .HasColumnName("email_body");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("boolean")
                        .HasColumnName("email_sent");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductPageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_page_url");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("WhatsAppBody")
                        .HasColumnType("text")
                        .HasColumnName("whats_app_body");

                    b.Property<bool>("WhatsAppSent")
                        .HasColumnType("boolean")
                        .HasColumnName("whats_app_sent");

                    b.HasKey("Id")
                        .HasName("pk_notification_history");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_notification_history_product_id");

                    b.ToTable("notification_history", (string)null);
                });

            modelBuilder.Entity("StoreScrapper.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdapterId")
                        .HasColumnType("integer")
                        .HasColumnName("adapter_id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("AvailabilityUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("availability_url");

                    b.Property<int>("CheckIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("check_interval_seconds");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("text")
                        .HasColumnName("hangfire_job_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ProductPageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_page_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("AdapterId")
                        .HasDatabaseName("ix_products_adapter_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("StoreScrapper.Models.Entities.ProductSku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("JobExecutionLogId")
                        .HasColumnType("integer")
                        .HasColumnName("job_execution_log_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Sku")
                        .HasColumnType("integer")
                        .HasColumnName("sku");

                    b.Property<bool>("TemporaryDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("temporary_disabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_product_skus");

                    b.HasIndex("JobExecutionLogId")
                        .HasDatabaseName("ix_product_skus_job_execution_log_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_skus_product_id");

                    b.ToTable("product_skus", (string)null);
                });

            modelBuilder.Entity("StoreScrapper.Models.Entities.ProductSkuReActivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<int>("ProductSkuId")
                        .HasColumnType("integer")
                        .HasColumnName("product_sku_id");

                    b.Property<string>("ReEnableUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("re_enable_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_product_sku_re_activations");

                    b.HasIndex("ProductSkuId")
                        .HasDatabaseName("ix_product_sku_re_activations_product_sku_id");

                    b.ToTable("product_sku_re_activations", (string)null);
                });

            modelBuilder.Entity("NotificationHistoryProductSku", b =>
                {
                    b.HasOne("StoreScrapper.Models.Entities.NotificationHistory", null)
                        .WithMany()
                        .HasForeignKey("NotificationHistoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_history_product_sku_notification_history_notif");

                    b.HasOne("StoreScrapper.Models.Entities.ProductSku", null)
                        .WithMany()
                        .HasForeignKey("ProductSkusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_history_product_sku_product_skus_product_skus_");
                });

            modelBuilder.Entity("StoreScrapper.Models.Entities.JobExecutionLog", b =>
                {
                    b.HasOne("StoreScrapper.Models.Entities.NotificationHistory", "NotificationHistory")
                        .WithMany()
                        .HasForeignKey("NotificationHistoryId")
                        .HasConstraintName("fk_job_execution_logs_notification_history_notification_histor");

                    b.HasOne("StoreScrapper.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_execution_logs_products_product_id");

                    b.Navigation("NotificationHistory");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreScrapper.Models.Entities.NotificationHistory", b =>
                {
                    b.HasOne("StoreScrapper.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_history_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreScrapper.Models.Entities.Product", b =>
                {
                    b.HasOne("StoreScrapper.Models.Entities.Adapter", "Adapter")
                        .WithMany()
                        .HasForeignKey("AdapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_adapters_adapter_id");

                    b.Navigation("Adapter");
                });

            modelBuilder.Entity("StoreScrapper.Models.Entities.ProductSku", b =>
                {
                    b.HasOne("StoreScrapper.Models.Entities.JobExecutionLog", null)
                        .WithMany("ProductSkus")
                        .HasForeignKey("JobExecutionLogId")
                        .HasConstraintName("fk_product_skus_job_execution_logs_job_execution_log_id");

                    b.HasOne("StoreScrapper.Models.Entities.Product", "Product")
                        .WithMany("ProductSkus")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_skus_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreScrapper.Models.Entities.ProductSkuReActivation", b =>
                {
                    b.HasOne("StoreScrapper.Models.Entities.ProductSku", "ProductSku")
                        .WithMany("ProductSkuReActivations")
                        .HasForeignKey("ProductSkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_sku_re_activations_product_skus_product_sku_id");

                    b.Navigation("ProductSku");
                });

            modelBuilder.Entity("StoreScrapper.Models.Entities.JobExecutionLog", b =>
                {
                    b.Navigation("ProductSkus");
                });

            modelBuilder.Entity("StoreScrapper.Models.Entities.Product", b =>
                {
                    b.Navigation("ProductSkus");
                });

            modelBuilder.Entity("StoreScrapper.Models.Entities.ProductSku", b =>
                {
                    b.Navigation("ProductSkuReActivations");
                });
#pragma warning restore 612, 618
        }
    }
}
